mode: MPIIFaceGaze
device: cpu
model:
  name: resnet_simple
  backbone:
    name: resnet_simple
    pretrained: resnet18
    resnet_block: basic
    resnet_layers: [2, 2, 2]
face_detector:
  mode: dlib
gaze_estimator:
  checkpoint: ~/.ptgaze/data/models/mpiifacegaze_resnet_simple.pth
  camera_params: ''
  normalized_camera_params: ''
  normalized_camera_distance: 1.0
demo:
  use_camera: True
  display_on_screen: True
  wait_time: 1
  image_path: ''
  video_path: ''
  output_dir: ''
  output_file_extension: avi
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.05
  show_bbox: True
  show_head_pose: False
  show_landmarks: False
  show_normalized_image: False
  show_template_model: False
